name: Build and Deploy

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install
      run: |
        npm install
        npm run build

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BASE_BRANCH: release # 要构建的分支
        BRANCH: master # 目标分支
        FOLDER: dist # 要发布的文件夹
